name: Quality checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint (Prettier + ESLint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node with version 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm install
      - name: Run linters
        run: npm run lint
